Implement and test tutorial event identifier
bubakazouba/remindmebot pull request #22
Opened 2020-11-05 21:08 UTC by arthurshir

- Put reminder command variants into shared constants file
- Fix bug in tutorials constants file
- Implement tutorial event identifier
- Write unit tests for tutorial event identifier

2020-11-05 21:10 UTC, bubakazouba commented on utils/constants.js
> +const REMINDME_MIDDLEWARE_VARIANTS = ['r', 'remind me', ...FRANCO_ARAB_REMINDME_VARIANTS];
this constant is not only used by the middleware

2020-11-05 21:11 UTC, bubakazouba commented on tutorial/event_identifier.js
> +const LAX_TZ = "America/Los_Angeles";
some comment explaining why ur hardcoding the timezone, i'm assuming the timezone doesn't matter here.

2020-11-05 21:12 UTC, bubakazouba commented on tst/tutorial/eventIdentifier.test.js
> +            '/remindlksfjdslkfj welrkj': null,
add 'race to the moon': null

that should fail

2020-11-05 21:14 UTC, arthurshir commented on tst/tutorial/eventIdentifier.test.js
> +            '/remindlksfjdslkfj welrkj': null,
Hmm good catch, that evaluates to INVALID_REMINDER which is a bug

2020-11-05 21:15 UTC, arthurshir commented on tutorial/event_identifier.js
> +const LAX_TZ = "America/Los_Angeles";
going to rename to "any_valid_tz"

2020-11-05 21:17 UTC, arthurshir commented on utils/constants.js
> +const REMINDME_MIDDLEWARE_VARIANTS = ['r', 'remind me', ...FRANCO_ARAB_REMINDME_VARIANTS];
Do you have any ideas for a better name for this? I was thinking something that indicates that this is used in the regex match... but had trouble coming up with a better name.

2020-11-05 21:19 UTC, bubakazouba requested changes

2020-11-05 21:19 UTC, bubakazouba commented on tutorial/event_identifier.js
> +function isBackslashCommand(utterance, commandStrings) {
forward* slash

2020-11-05 21:19 UTC, bubakazouba commented on tutorial/event_identifier.js
> +function isValidTimezoneCommand(utterance){
use `_` to mark private functions (same for other files)

2020-11-05 21:19 UTC, bubakazouba commented on tst/tutorial/eventIdentifier.test.js
> +            '/remindlksfjdslkfj welrkj': null,
add an edge case for empty string

2020-11-05 21:19 UTC, bubakazouba commented on tutorial/event_identifier.js
> +    let timezoneInput = utterance.split(" ").slice(1).join(" "); // remove the first word ("/timezone")
can you think of a way to resolve the redundancy here? If this logic changes we have 2 places to change it

maybe something as simple as moving this inside `parseTimezone`

2020-11-05 21:19 UTC, bubakazouba commented on tutorial/event_identifier.js
> +const TIMEZONE_COMMAND_VARIANTS = ["timezone"];
move to shared constants and have it used in timezonecommand.js

2020-11-05 21:19 UTC, arthurshir commented
Add `_` prefix to "private" functions

2020-11-05 21:21 UTC, arthurshir commented on tutorial/event_identifier.js
> +    let timezoneInput = utterance.split(" ").slice(1).join(" "); // remove the first word ("/timezone")
Yes, I'll do some refactoring to parseTimezone

2020-11-05 21:22 UTC, arthurshir commented on tutorial/event_identifier.js
> +const TIMEZONE_COMMAND_VARIANTS = ["timezone"];
Yes good call. I was feeling hesitant about modifying the code of other files. But, since we have comprehensive testing I should overcome this feeling of hesitation.

2020-11-11 05:39 UTC, bubakazouba commented on README.md
> +    - ...
Remove the `...`, add a TODO if you meant to do this later

2020-11-11 05:39 UTC, bubakazouba commented on botfunctions/constants.js
> +const TIMEZONE_COMMAND_VARIANTS = ['timezone'];
add `settimezone`

2020-11-11 05:40 UTC, bubakazouba commented on botfunctions/timezonecommand.js
> +
Nit replace 2 extra lines with just 1 extra line

2020-11-11 05:46 UTC, bubakazouba commented on botfunctions/remindercommand.js
>          bot.command(commandVariant, remindmeCallBack);
is this going to be a problem for telegraf if we give it a command that contains spaces?
I'm assuming you ran the bot after this commit so just confirm that the bot ran successfully and processed any commands

2020-11-11 05:53 UTC, bubakazouba commented on botfunctions/timezonecommand.js
> +    stripCommandFromUtterance: stripCommandFromUtterance,
we shouldn't need to export stripCommandFromUtterance

2020-11-11 05:59 UTC, bubakazouba commented on tst/botfunctions/timezonecommand.test.js
> +            '/timezonesdf sdf': false,
add just 1 more for /settimezone

2020-11-11 06:02 UTC, arthurshir commented on botfunctions/timezonecommand.js
> +    stripCommandFromUtterance: stripCommandFromUtterance,
Shouldn't we use it in `msgr/handler.js`?

2020-11-11 06:04 UTC, bubakazouba commented on botfunctions/timezonecommand.js
> +    stripCommandFromUtterance: stripCommandFromUtterance,
ah ur right, `parseTimezone` takes `commandInput` not `utterance`

2020-11-14 04:02 UTC, arthurshir commented on botfunctions/remindercommand.js
>          bot.command(commandVariant, remindmeCallBack);
Tested, no problem.

note: adding `remind` to variants.
note: variants with spaces are not added as commands to the bot.

2020-11-14 04:15 UTC, bubakazouba approved these changes

2020-11-14 04:15 UTC, merged